<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-03-16 14:09

$extensionPath = t3lib_extMgm::extPath('sitemgr');
$extensionClassesPath = t3lib_extMgm::extPath('sitemgr') . 'Classes/';
return array(
	'tx_sitemgr_controller_sitemanagercontroller' => $extensionClassesPath . 'Controller/SiteManager.php',
	'tx_sitemgr_extdirect_dispatcher' => $extensionClassesPath . 'ExtDirect/Dispatcher.php',
	'tx_sitemgr_extmgm_abstractupdater' => $extensionClassesPath . 'ExtMgm/AbstractUpdater.php',
	'tx_sitemgr_extmgm_updater' => $extensionClassesPath . 'ExtMgm/Updater.php',
	'tx_sitemgr_toolbaritems_customerselector_item' => $extensionClassesPath . 'ToolbarItems/CustomerSelector/Item.php',
);
?>