<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-03-16 17:49

$extensionPath = t3lib_extMgm::extPath('sitemgr');
$extensionClassesPath = t3lib_extMgm::extPath('sitemgr') . 'Classes/';
return array(
	'tx_sitemgr_controller_sitemanagercontroller' => $extensionClassesPath . 'Controller/SiteManager.php',
	'tx_sitemgr_extdirect_dispatcher' => $extensionClassesPath . 'ExtDirect/Dispatcher.php',
	'tx_sitemgr_extmgm_abstractupdater' => $extensionClassesPath . 'ExtMgm/AbstractUpdater.php',
	'tx_sitemgr_extmgm_updater' => $extensionClassesPath . 'ExtMgm/Updater.php',
	'tx_sitemgr_toolbaritems_customerselector_item' => $extensionClassesPath . 'ToolbarItems/CustomerSelector/Item.php',
	'tx_sitemgr_viewhelpers_be_doc_addcssfileviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/Doc/AddCssFile.php',
	'tx_sitemgr_viewhelpers_be_doc_addinlinelanguagelabelfileviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/Doc/AddInlineLanguageLabelFile.php',
	'tx_sitemgr_viewhelpers_be_doc_addinlinesettingarrayviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/Doc/AddInlineSettingArray.php',
	'tx_sitemgr_viewhelpers_be_doc_addjsfileviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/Doc/AddJsFile.php',
);
?>